# Generated by Django 2.0.2 on 2021-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_auto_20210305_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publishing',
            name='condition',
            field=models.IntegerField(choices=[('0', 'Car'), ('1', 'Suv')], default=0),
        ),
        migrations.AddField(
            model_name='publishing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishing',
            name='tel',
            field=models.TextField(blank=True),
        ),
    ]
