# Generated by Django 2.0.2 on 2021-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0005_auto_20210306_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
