# Generated by Django 2.0.2 on 2021-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0007_auto_20210322_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishing',
            old_name='icon',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='publishing',
            old_name='image',
            new_name='image2',
        ),
        migrations.AddField(
            model_name='publishing',
            name='image3',
            field=models.ImageField(blank=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='publishing',
            name='image4',
            field=models.ImageField(blank=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='publishing',
            name='image5',
            field=models.ImageField(blank=True, upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='category',
            field=models.TextField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='condition',
            field=models.TextField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fairly Good', 'Fairly Good'), ('Fairly Poor', 'Fairly Poor'), ('Poor', 'Poor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='fuel',
            field=models.TextField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric(ECV)', 'Electric(ECV)'), ('Hybrid(HEV)', 'Hybrid(HEV)'), ('LPG Autogas', 'LPG Autogas'), ('Biofuel', 'Biofuel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='transmission',
            field=models.TextField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'CVT')], max_length=100),
        ),
    ]
