# Generated by Django 2.0.2 on 2021-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0010_auto_20210322_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='image1',
            field=models.ImageField(upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image2',
            field=models.ImageField(upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image3',
            field=models.ImageField(upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image4',
            field=models.ImageField(upload_to='upload_to=images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='image5',
            field=models.ImageField(upload_to='upload_to=images/%Y/%m/%d/'),
        ),
    ]
