# Generated by Django 2.0.2 on 2021-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0011_auto_20210322_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='brand',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='engine',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='milage',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='model',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='tel',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(max_length=100),
        ),
    ]
