# Generated by Django 2.0.2 on 2021-03-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0012_auto_20210323_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='milage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(),
        ),
    ]
