# Generated by Django 2.0.2 on 2021-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0013_auto_20210323_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
