# Generated by Django 2.0.2 on 2021-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0016_auto_20210330_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='type',
            field=models.TextField(choices=[('Motorbike', 'Motorbike'), ('Motorbike-Scooter', 'Motorbike-Scooter'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('MPV/Minivan', 'MPV/Minivan'), ('SUV', 'SUV'), ('CUV/Crossover', 'CUV/Crossover'), ('Pickup', 'Pickup'), ('Coupe', 'Coupe'), ('Convertible/Cabriolet', 'Convertible/Cabriolet'), ('Station Wagon/Estate', 'Station Wagon/Estate'), ('Van', 'Van'), ('Three-Wheeler', 'Three-Wheeler'), ('Lorry', 'Lorry'), ('Bus', 'Bus')], max_length=100),
        ),
    ]
